//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsumer_Thin.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Shippers_SaveCollection", ReplyAction="http://tempuri.org/IService1/Shippers_SaveCollectionResponse")]
        Proxies.ShippersCollectionProxyStub Shippers_SaveCollection(Proxies.ShippersCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Shippers_SaveEntity", ReplyAction="http://tempuri.org/IService1/Shippers_SaveEntityResponse")]
        Proxies.ShippersProxyStub Shippers_SaveEntity(Proxies.ShippersProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suppliers_LoadAll", ReplyAction="http://tempuri.org/IService1/Suppliers_LoadAllResponse")]
        Proxies.SuppliersCollectionProxyStub Suppliers_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suppliers_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Suppliers_QueryForCollectionResponse")]
        Proxies.SuppliersCollectionProxyStub Suppliers_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suppliers_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Suppliers_QueryForEntityResponse")]
        Proxies.SuppliersProxyStub Suppliers_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suppliers_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Suppliers_GetByPrimaryKeyResponse")]
        Proxies.SuppliersProxyStub Suppliers_GetByPrimaryKey(int supplierID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suppliers_SaveCollection", ReplyAction="http://tempuri.org/IService1/Suppliers_SaveCollectionResponse")]
        Proxies.SuppliersCollectionProxyStub Suppliers_SaveCollection(Proxies.SuppliersCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Suppliers_SaveEntity", ReplyAction="http://tempuri.org/IService1/Suppliers_SaveEntityResponse")]
        Proxies.SuppliersProxyStub Suppliers_SaveEntity(Proxies.SuppliersProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Territories_LoadAll", ReplyAction="http://tempuri.org/IService1/Territories_LoadAllResponse")]
        Proxies.TerritoriesCollectionProxyStub Territories_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Territories_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Territories_QueryForCollectionResponse")]
        Proxies.TerritoriesCollectionProxyStub Territories_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Territories_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Territories_QueryForEntityResponse")]
        Proxies.TerritoriesProxyStub Territories_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Territories_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Territories_GetByPrimaryKeyResponse")]
        Proxies.TerritoriesProxyStub Territories_GetByPrimaryKey(string territoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Territories_SaveCollection", ReplyAction="http://tempuri.org/IService1/Territories_SaveCollectionResponse")]
        Proxies.TerritoriesCollectionProxyStub Territories_SaveCollection(Proxies.TerritoriesCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Territories_SaveEntity", ReplyAction="http://tempuri.org/IService1/Territories_SaveEntityResponse")]
        Proxies.TerritoriesProxyStub Territories_SaveEntity(Proxies.TerritoriesProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeTerritories_QueryForEntity", ReplyAction="http://tempuri.org/IService1/EmployeeTerritories_QueryForEntityResponse")]
        Proxies.EmployeeTerritoriesProxyStub EmployeeTerritories_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeTerritories_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/EmployeeTerritories_GetByPrimaryKeyResponse")]
        Proxies.EmployeeTerritoriesProxyStub EmployeeTerritories_GetByPrimaryKey(int employeeID, string territoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeTerritories_SaveCollection", ReplyAction="http://tempuri.org/IService1/EmployeeTerritories_SaveCollectionResponse")]
        Proxies.EmployeeTerritoriesCollectionProxyStub EmployeeTerritories_SaveCollection(Proxies.EmployeeTerritoriesCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeTerritories_SaveEntity", ReplyAction="http://tempuri.org/IService1/EmployeeTerritories_SaveEntityResponse")]
        Proxies.EmployeeTerritoriesProxyStub EmployeeTerritories_SaveEntity(Proxies.EmployeeTerritoriesProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderDetails_LoadAll", ReplyAction="http://tempuri.org/IService1/OrderDetails_LoadAllResponse")]
        Proxies.OrderDetailsCollectionProxyStub OrderDetails_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderDetails_QueryForCollection", ReplyAction="http://tempuri.org/IService1/OrderDetails_QueryForCollectionResponse")]
        Proxies.OrderDetailsCollectionProxyStub OrderDetails_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderDetails_QueryForEntity", ReplyAction="http://tempuri.org/IService1/OrderDetails_QueryForEntityResponse")]
        Proxies.OrderDetailsProxyStub OrderDetails_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderDetails_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/OrderDetails_GetByPrimaryKeyResponse")]
        Proxies.OrderDetailsProxyStub OrderDetails_GetByPrimaryKey(int orderID, int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderDetails_SaveCollection", ReplyAction="http://tempuri.org/IService1/OrderDetails_SaveCollectionResponse")]
        Proxies.OrderDetailsCollectionProxyStub OrderDetails_SaveCollection(Proxies.OrderDetailsCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderDetails_SaveEntity", ReplyAction="http://tempuri.org/IService1/OrderDetails_SaveEntityResponse")]
        Proxies.OrderDetailsProxyStub OrderDetails_SaveEntity(Proxies.OrderDetailsProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_LoadAll", ReplyAction="http://tempuri.org/IService1/Orders_LoadAllResponse")]
        Proxies.OrdersCollectionProxyStub Orders_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Orders_QueryForCollectionResponse")]
        Proxies.OrdersCollectionProxyStub Orders_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Orders_QueryForEntityResponse")]
        Proxies.OrdersProxyStub Orders_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Orders_GetByPrimaryKeyResponse")]
        Proxies.OrdersProxyStub Orders_GetByPrimaryKey(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_SaveCollection", ReplyAction="http://tempuri.org/IService1/Orders_SaveCollectionResponse")]
        Proxies.OrdersCollectionProxyStub Orders_SaveCollection(Proxies.OrdersCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_SaveEntity", ReplyAction="http://tempuri.org/IService1/Orders_SaveEntityResponse")]
        Proxies.OrdersProxyStub Orders_SaveEntity(Proxies.OrdersProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products_LoadAll", ReplyAction="http://tempuri.org/IService1/Products_LoadAllResponse")]
        Proxies.ProductsCollectionProxyStub Products_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Products_QueryForCollectionResponse")]
        Proxies.ProductsCollectionProxyStub Products_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Products_QueryForEntityResponse")]
        Proxies.ProductsProxyStub Products_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Products_GetByPrimaryKeyResponse")]
        Proxies.ProductsProxyStub Products_GetByPrimaryKey(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products_SaveCollection", ReplyAction="http://tempuri.org/IService1/Products_SaveCollectionResponse")]
        Proxies.ProductsCollectionProxyStub Products_SaveCollection(Proxies.ProductsCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Products_SaveEntity", ReplyAction="http://tempuri.org/IService1/Products_SaveEntityResponse")]
        Proxies.ProductsProxyStub Products_SaveEntity(Proxies.ProductsProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Region_LoadAll", ReplyAction="http://tempuri.org/IService1/Region_LoadAllResponse")]
        Proxies.RegionCollectionProxyStub Region_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Region_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Region_QueryForCollectionResponse")]
        Proxies.RegionCollectionProxyStub Region_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Region_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Region_QueryForEntityResponse")]
        Proxies.RegionProxyStub Region_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Region_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Region_GetByPrimaryKeyResponse")]
        Proxies.RegionProxyStub Region_GetByPrimaryKey(int regionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Region_SaveCollection", ReplyAction="http://tempuri.org/IService1/Region_SaveCollectionResponse")]
        Proxies.RegionCollectionProxyStub Region_SaveCollection(Proxies.RegionCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Region_SaveEntity", ReplyAction="http://tempuri.org/IService1/Region_SaveEntityResponse")]
        Proxies.RegionProxyStub Region_SaveEntity(Proxies.RegionProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Shippers_LoadAll", ReplyAction="http://tempuri.org/IService1/Shippers_LoadAllResponse")]
        Proxies.ShippersCollectionProxyStub Shippers_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Shippers_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Shippers_QueryForCollectionResponse")]
        Proxies.ShippersCollectionProxyStub Shippers_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Shippers_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Shippers_QueryForEntityResponse")]
        Proxies.ShippersProxyStub Shippers_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Shippers_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Shippers_GetByPrimaryKeyResponse")]
        Proxies.ShippersProxyStub Shippers_GetByPrimaryKey(int shipperID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Categories_LoadAll", ReplyAction="http://tempuri.org/IService1/Categories_LoadAllResponse")]
        Proxies.CategoriesCollectionProxyStub Categories_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Categories_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Categories_QueryForCollectionResponse")]
        Proxies.CategoriesCollectionProxyStub Categories_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Categories_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Categories_QueryForEntityResponse")]
        Proxies.CategoriesProxyStub Categories_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Categories_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Categories_GetByPrimaryKeyResponse")]
        Proxies.CategoriesProxyStub Categories_GetByPrimaryKey(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Categories_SaveCollection", ReplyAction="http://tempuri.org/IService1/Categories_SaveCollectionResponse")]
        Proxies.CategoriesCollectionProxyStub Categories_SaveCollection(Proxies.CategoriesCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Categories_SaveEntity", ReplyAction="http://tempuri.org/IService1/Categories_SaveEntityResponse")]
        Proxies.CategoriesProxyStub Categories_SaveEntity(Proxies.CategoriesProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCustomerDemo_LoadAll", ReplyAction="http://tempuri.org/IService1/CustomerCustomerDemo_LoadAllResponse")]
        Proxies.CustomerCustomerDemoCollectionProxyStub CustomerCustomerDemo_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCustomerDemo_QueryForCollection", ReplyAction="http://tempuri.org/IService1/CustomerCustomerDemo_QueryForCollectionResponse")]
        Proxies.CustomerCustomerDemoCollectionProxyStub CustomerCustomerDemo_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCustomerDemo_QueryForEntity", ReplyAction="http://tempuri.org/IService1/CustomerCustomerDemo_QueryForEntityResponse")]
        Proxies.CustomerCustomerDemoProxyStub CustomerCustomerDemo_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCustomerDemo_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/CustomerCustomerDemo_GetByPrimaryKeyResponse")]
        Proxies.CustomerCustomerDemoProxyStub CustomerCustomerDemo_GetByPrimaryKey(string customerID, string customerTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCustomerDemo_SaveCollection", ReplyAction="http://tempuri.org/IService1/CustomerCustomerDemo_SaveCollectionResponse")]
        Proxies.CustomerCustomerDemoCollectionProxyStub CustomerCustomerDemo_SaveCollection(Proxies.CustomerCustomerDemoCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerCustomerDemo_SaveEntity", ReplyAction="http://tempuri.org/IService1/CustomerCustomerDemo_SaveEntityResponse")]
        Proxies.CustomerCustomerDemoProxyStub CustomerCustomerDemo_SaveEntity(Proxies.CustomerCustomerDemoProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerDemographics_LoadAll", ReplyAction="http://tempuri.org/IService1/CustomerDemographics_LoadAllResponse")]
        Proxies.CustomerDemographicsCollectionProxyStub CustomerDemographics_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerDemographics_QueryForCollection", ReplyAction="http://tempuri.org/IService1/CustomerDemographics_QueryForCollectionResponse")]
        Proxies.CustomerDemographicsCollectionProxyStub CustomerDemographics_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerDemographics_QueryForEntity", ReplyAction="http://tempuri.org/IService1/CustomerDemographics_QueryForEntityResponse")]
        Proxies.CustomerDemographicsProxyStub CustomerDemographics_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerDemographics_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/CustomerDemographics_GetByPrimaryKeyResponse")]
        Proxies.CustomerDemographicsProxyStub CustomerDemographics_GetByPrimaryKey(string customerTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerDemographics_SaveCollection", ReplyAction="http://tempuri.org/IService1/CustomerDemographics_SaveCollectionResponse")]
        Proxies.CustomerDemographicsCollectionProxyStub CustomerDemographics_SaveCollection(Proxies.CustomerDemographicsCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CustomerDemographics_SaveEntity", ReplyAction="http://tempuri.org/IService1/CustomerDemographics_SaveEntityResponse")]
        Proxies.CustomerDemographicsProxyStub CustomerDemographics_SaveEntity(Proxies.CustomerDemographicsProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Customers_LoadAll", ReplyAction="http://tempuri.org/IService1/Customers_LoadAllResponse")]
        Proxies.CustomersCollectionProxyStub Customers_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Customers_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Customers_QueryForCollectionResponse")]
        Proxies.CustomersCollectionProxyStub Customers_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Customers_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Customers_QueryForEntityResponse")]
        Proxies.CustomersProxyStub Customers_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Customers_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Customers_GetByPrimaryKeyResponse")]
        Proxies.CustomersProxyStub Customers_GetByPrimaryKey(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Customers_SaveCollection", ReplyAction="http://tempuri.org/IService1/Customers_SaveCollectionResponse")]
        Proxies.CustomersCollectionProxyStub Customers_SaveCollection(Proxies.CustomersCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Customers_SaveEntity", ReplyAction="http://tempuri.org/IService1/Customers_SaveEntityResponse")]
        Proxies.CustomersProxyStub Customers_SaveEntity(Proxies.CustomersProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Employees_LoadAll", ReplyAction="http://tempuri.org/IService1/Employees_LoadAllResponse")]
        Proxies.EmployeesCollectionProxyStub Employees_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Employees_QueryForCollection", ReplyAction="http://tempuri.org/IService1/Employees_QueryForCollectionResponse")]
        Proxies.EmployeesCollectionProxyStub Employees_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Employees_QueryForEntity", ReplyAction="http://tempuri.org/IService1/Employees_QueryForEntityResponse")]
        Proxies.EmployeesProxyStub Employees_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Employees_GetByPrimaryKey", ReplyAction="http://tempuri.org/IService1/Employees_GetByPrimaryKeyResponse")]
        Proxies.EmployeesProxyStub Employees_GetByPrimaryKey(int employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Employees_SaveCollection", ReplyAction="http://tempuri.org/IService1/Employees_SaveCollectionResponse")]
        Proxies.EmployeesCollectionProxyStub Employees_SaveCollection(Proxies.EmployeesCollectionProxyStub collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Employees_SaveEntity", ReplyAction="http://tempuri.org/IService1/Employees_SaveEntityResponse")]
        Proxies.EmployeesProxyStub Employees_SaveEntity(Proxies.EmployeesProxyStub entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeTerritories_LoadAll", ReplyAction="http://tempuri.org/IService1/EmployeeTerritories_LoadAllResponse")]
        Proxies.EmployeeTerritoriesCollectionProxyStub EmployeeTerritories_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EmployeeTerritories_QueryForCollection", ReplyAction="http://tempuri.org/IService1/EmployeeTerritories_QueryForCollectionResponse")]
        Proxies.EmployeeTerritoriesCollectionProxyStub EmployeeTerritories_QueryForCollection(string serializedQuery);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IService1Channel : WCFConsumer_Thin.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFConsumer_Thin.ServiceReference1.IService1>, WCFConsumer_Thin.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Proxies.ShippersCollectionProxyStub Shippers_SaveCollection(Proxies.ShippersCollectionProxyStub collection) {
            return base.Channel.Shippers_SaveCollection(collection);
        }
        
        public Proxies.ShippersProxyStub Shippers_SaveEntity(Proxies.ShippersProxyStub entity) {
            return base.Channel.Shippers_SaveEntity(entity);
        }
        
        public Proxies.SuppliersCollectionProxyStub Suppliers_LoadAll() {
            return base.Channel.Suppliers_LoadAll();
        }
        
        public Proxies.SuppliersCollectionProxyStub Suppliers_QueryForCollection(string serializedQuery) {
            return base.Channel.Suppliers_QueryForCollection(serializedQuery);
        }
        
        public Proxies.SuppliersProxyStub Suppliers_QueryForEntity(string serializedQuery) {
            return base.Channel.Suppliers_QueryForEntity(serializedQuery);
        }
        
        public Proxies.SuppliersProxyStub Suppliers_GetByPrimaryKey(int supplierID) {
            return base.Channel.Suppliers_GetByPrimaryKey(supplierID);
        }
        
        public Proxies.SuppliersCollectionProxyStub Suppliers_SaveCollection(Proxies.SuppliersCollectionProxyStub collection) {
            return base.Channel.Suppliers_SaveCollection(collection);
        }
        
        public Proxies.SuppliersProxyStub Suppliers_SaveEntity(Proxies.SuppliersProxyStub entity) {
            return base.Channel.Suppliers_SaveEntity(entity);
        }
        
        public Proxies.TerritoriesCollectionProxyStub Territories_LoadAll() {
            return base.Channel.Territories_LoadAll();
        }
        
        public Proxies.TerritoriesCollectionProxyStub Territories_QueryForCollection(string serializedQuery) {
            return base.Channel.Territories_QueryForCollection(serializedQuery);
        }
        
        public Proxies.TerritoriesProxyStub Territories_QueryForEntity(string serializedQuery) {
            return base.Channel.Territories_QueryForEntity(serializedQuery);
        }
        
        public Proxies.TerritoriesProxyStub Territories_GetByPrimaryKey(string territoryID) {
            return base.Channel.Territories_GetByPrimaryKey(territoryID);
        }
        
        public Proxies.TerritoriesCollectionProxyStub Territories_SaveCollection(Proxies.TerritoriesCollectionProxyStub collection) {
            return base.Channel.Territories_SaveCollection(collection);
        }
        
        public Proxies.TerritoriesProxyStub Territories_SaveEntity(Proxies.TerritoriesProxyStub entity) {
            return base.Channel.Territories_SaveEntity(entity);
        }
        
        public Proxies.EmployeeTerritoriesProxyStub EmployeeTerritories_QueryForEntity(string serializedQuery) {
            return base.Channel.EmployeeTerritories_QueryForEntity(serializedQuery);
        }
        
        public Proxies.EmployeeTerritoriesProxyStub EmployeeTerritories_GetByPrimaryKey(int employeeID, string territoryID) {
            return base.Channel.EmployeeTerritories_GetByPrimaryKey(employeeID, territoryID);
        }
        
        public Proxies.EmployeeTerritoriesCollectionProxyStub EmployeeTerritories_SaveCollection(Proxies.EmployeeTerritoriesCollectionProxyStub collection) {
            return base.Channel.EmployeeTerritories_SaveCollection(collection);
        }
        
        public Proxies.EmployeeTerritoriesProxyStub EmployeeTerritories_SaveEntity(Proxies.EmployeeTerritoriesProxyStub entity) {
            return base.Channel.EmployeeTerritories_SaveEntity(entity);
        }
        
        public Proxies.OrderDetailsCollectionProxyStub OrderDetails_LoadAll() {
            return base.Channel.OrderDetails_LoadAll();
        }
        
        public Proxies.OrderDetailsCollectionProxyStub OrderDetails_QueryForCollection(string serializedQuery) {
            return base.Channel.OrderDetails_QueryForCollection(serializedQuery);
        }
        
        public Proxies.OrderDetailsProxyStub OrderDetails_QueryForEntity(string serializedQuery) {
            return base.Channel.OrderDetails_QueryForEntity(serializedQuery);
        }
        
        public Proxies.OrderDetailsProxyStub OrderDetails_GetByPrimaryKey(int orderID, int productID) {
            return base.Channel.OrderDetails_GetByPrimaryKey(orderID, productID);
        }
        
        public Proxies.OrderDetailsCollectionProxyStub OrderDetails_SaveCollection(Proxies.OrderDetailsCollectionProxyStub collection) {
            return base.Channel.OrderDetails_SaveCollection(collection);
        }
        
        public Proxies.OrderDetailsProxyStub OrderDetails_SaveEntity(Proxies.OrderDetailsProxyStub entity) {
            return base.Channel.OrderDetails_SaveEntity(entity);
        }
        
        public Proxies.OrdersCollectionProxyStub Orders_LoadAll() {
            return base.Channel.Orders_LoadAll();
        }
        
        public Proxies.OrdersCollectionProxyStub Orders_QueryForCollection(string serializedQuery) {
            return base.Channel.Orders_QueryForCollection(serializedQuery);
        }
        
        public Proxies.OrdersProxyStub Orders_QueryForEntity(string serializedQuery) {
            return base.Channel.Orders_QueryForEntity(serializedQuery);
        }
        
        public Proxies.OrdersProxyStub Orders_GetByPrimaryKey(int orderID) {
            return base.Channel.Orders_GetByPrimaryKey(orderID);
        }
        
        public Proxies.OrdersCollectionProxyStub Orders_SaveCollection(Proxies.OrdersCollectionProxyStub collection) {
            return base.Channel.Orders_SaveCollection(collection);
        }
        
        public Proxies.OrdersProxyStub Orders_SaveEntity(Proxies.OrdersProxyStub entity) {
            return base.Channel.Orders_SaveEntity(entity);
        }
        
        public Proxies.ProductsCollectionProxyStub Products_LoadAll() {
            return base.Channel.Products_LoadAll();
        }
        
        public Proxies.ProductsCollectionProxyStub Products_QueryForCollection(string serializedQuery) {
            return base.Channel.Products_QueryForCollection(serializedQuery);
        }
        
        public Proxies.ProductsProxyStub Products_QueryForEntity(string serializedQuery) {
            return base.Channel.Products_QueryForEntity(serializedQuery);
        }
        
        public Proxies.ProductsProxyStub Products_GetByPrimaryKey(int productID) {
            return base.Channel.Products_GetByPrimaryKey(productID);
        }
        
        public Proxies.ProductsCollectionProxyStub Products_SaveCollection(Proxies.ProductsCollectionProxyStub collection) {
            return base.Channel.Products_SaveCollection(collection);
        }
        
        public Proxies.ProductsProxyStub Products_SaveEntity(Proxies.ProductsProxyStub entity) {
            return base.Channel.Products_SaveEntity(entity);
        }
        
        public Proxies.RegionCollectionProxyStub Region_LoadAll() {
            return base.Channel.Region_LoadAll();
        }
        
        public Proxies.RegionCollectionProxyStub Region_QueryForCollection(string serializedQuery) {
            return base.Channel.Region_QueryForCollection(serializedQuery);
        }
        
        public Proxies.RegionProxyStub Region_QueryForEntity(string serializedQuery) {
            return base.Channel.Region_QueryForEntity(serializedQuery);
        }
        
        public Proxies.RegionProxyStub Region_GetByPrimaryKey(int regionID) {
            return base.Channel.Region_GetByPrimaryKey(regionID);
        }
        
        public Proxies.RegionCollectionProxyStub Region_SaveCollection(Proxies.RegionCollectionProxyStub collection) {
            return base.Channel.Region_SaveCollection(collection);
        }
        
        public Proxies.RegionProxyStub Region_SaveEntity(Proxies.RegionProxyStub entity) {
            return base.Channel.Region_SaveEntity(entity);
        }
        
        public Proxies.ShippersCollectionProxyStub Shippers_LoadAll() {
            return base.Channel.Shippers_LoadAll();
        }
        
        public Proxies.ShippersCollectionProxyStub Shippers_QueryForCollection(string serializedQuery) {
            return base.Channel.Shippers_QueryForCollection(serializedQuery);
        }
        
        public Proxies.ShippersProxyStub Shippers_QueryForEntity(string serializedQuery) {
            return base.Channel.Shippers_QueryForEntity(serializedQuery);
        }
        
        public Proxies.ShippersProxyStub Shippers_GetByPrimaryKey(int shipperID) {
            return base.Channel.Shippers_GetByPrimaryKey(shipperID);
        }
        
        public Proxies.CategoriesCollectionProxyStub Categories_LoadAll() {
            return base.Channel.Categories_LoadAll();
        }
        
        public Proxies.CategoriesCollectionProxyStub Categories_QueryForCollection(string serializedQuery) {
            return base.Channel.Categories_QueryForCollection(serializedQuery);
        }
        
        public Proxies.CategoriesProxyStub Categories_QueryForEntity(string serializedQuery) {
            return base.Channel.Categories_QueryForEntity(serializedQuery);
        }
        
        public Proxies.CategoriesProxyStub Categories_GetByPrimaryKey(int categoryID) {
            return base.Channel.Categories_GetByPrimaryKey(categoryID);
        }
        
        public Proxies.CategoriesCollectionProxyStub Categories_SaveCollection(Proxies.CategoriesCollectionProxyStub collection) {
            return base.Channel.Categories_SaveCollection(collection);
        }
        
        public Proxies.CategoriesProxyStub Categories_SaveEntity(Proxies.CategoriesProxyStub entity) {
            return base.Channel.Categories_SaveEntity(entity);
        }
        
        public Proxies.CustomerCustomerDemoCollectionProxyStub CustomerCustomerDemo_LoadAll() {
            return base.Channel.CustomerCustomerDemo_LoadAll();
        }
        
        public Proxies.CustomerCustomerDemoCollectionProxyStub CustomerCustomerDemo_QueryForCollection(string serializedQuery) {
            return base.Channel.CustomerCustomerDemo_QueryForCollection(serializedQuery);
        }
        
        public Proxies.CustomerCustomerDemoProxyStub CustomerCustomerDemo_QueryForEntity(string serializedQuery) {
            return base.Channel.CustomerCustomerDemo_QueryForEntity(serializedQuery);
        }
        
        public Proxies.CustomerCustomerDemoProxyStub CustomerCustomerDemo_GetByPrimaryKey(string customerID, string customerTypeID) {
            return base.Channel.CustomerCustomerDemo_GetByPrimaryKey(customerID, customerTypeID);
        }
        
        public Proxies.CustomerCustomerDemoCollectionProxyStub CustomerCustomerDemo_SaveCollection(Proxies.CustomerCustomerDemoCollectionProxyStub collection) {
            return base.Channel.CustomerCustomerDemo_SaveCollection(collection);
        }
        
        public Proxies.CustomerCustomerDemoProxyStub CustomerCustomerDemo_SaveEntity(Proxies.CustomerCustomerDemoProxyStub entity) {
            return base.Channel.CustomerCustomerDemo_SaveEntity(entity);
        }
        
        public Proxies.CustomerDemographicsCollectionProxyStub CustomerDemographics_LoadAll() {
            return base.Channel.CustomerDemographics_LoadAll();
        }
        
        public Proxies.CustomerDemographicsCollectionProxyStub CustomerDemographics_QueryForCollection(string serializedQuery) {
            return base.Channel.CustomerDemographics_QueryForCollection(serializedQuery);
        }
        
        public Proxies.CustomerDemographicsProxyStub CustomerDemographics_QueryForEntity(string serializedQuery) {
            return base.Channel.CustomerDemographics_QueryForEntity(serializedQuery);
        }
        
        public Proxies.CustomerDemographicsProxyStub CustomerDemographics_GetByPrimaryKey(string customerTypeID) {
            return base.Channel.CustomerDemographics_GetByPrimaryKey(customerTypeID);
        }
        
        public Proxies.CustomerDemographicsCollectionProxyStub CustomerDemographics_SaveCollection(Proxies.CustomerDemographicsCollectionProxyStub collection) {
            return base.Channel.CustomerDemographics_SaveCollection(collection);
        }
        
        public Proxies.CustomerDemographicsProxyStub CustomerDemographics_SaveEntity(Proxies.CustomerDemographicsProxyStub entity) {
            return base.Channel.CustomerDemographics_SaveEntity(entity);
        }
        
        public Proxies.CustomersCollectionProxyStub Customers_LoadAll() {
            return base.Channel.Customers_LoadAll();
        }
        
        public Proxies.CustomersCollectionProxyStub Customers_QueryForCollection(string serializedQuery) {
            return base.Channel.Customers_QueryForCollection(serializedQuery);
        }
        
        public Proxies.CustomersProxyStub Customers_QueryForEntity(string serializedQuery) {
            return base.Channel.Customers_QueryForEntity(serializedQuery);
        }
        
        public Proxies.CustomersProxyStub Customers_GetByPrimaryKey(string customerID) {
            return base.Channel.Customers_GetByPrimaryKey(customerID);
        }
        
        public Proxies.CustomersCollectionProxyStub Customers_SaveCollection(Proxies.CustomersCollectionProxyStub collection) {
            return base.Channel.Customers_SaveCollection(collection);
        }
        
        public Proxies.CustomersProxyStub Customers_SaveEntity(Proxies.CustomersProxyStub entity) {
            return base.Channel.Customers_SaveEntity(entity);
        }
        
        public Proxies.EmployeesCollectionProxyStub Employees_LoadAll() {
            return base.Channel.Employees_LoadAll();
        }
        
        public Proxies.EmployeesCollectionProxyStub Employees_QueryForCollection(string serializedQuery) {
            return base.Channel.Employees_QueryForCollection(serializedQuery);
        }
        
        public Proxies.EmployeesProxyStub Employees_QueryForEntity(string serializedQuery) {
            return base.Channel.Employees_QueryForEntity(serializedQuery);
        }
        
        public Proxies.EmployeesProxyStub Employees_GetByPrimaryKey(int employeeID) {
            return base.Channel.Employees_GetByPrimaryKey(employeeID);
        }
        
        public Proxies.EmployeesCollectionProxyStub Employees_SaveCollection(Proxies.EmployeesCollectionProxyStub collection) {
            return base.Channel.Employees_SaveCollection(collection);
        }
        
        public Proxies.EmployeesProxyStub Employees_SaveEntity(Proxies.EmployeesProxyStub entity) {
            return base.Channel.Employees_SaveEntity(entity);
        }
        
        public Proxies.EmployeeTerritoriesCollectionProxyStub EmployeeTerritories_LoadAll() {
            return base.Channel.EmployeeTerritories_LoadAll();
        }
        
        public Proxies.EmployeeTerritoriesCollectionProxyStub EmployeeTerritories_QueryForCollection(string serializedQuery) {
            return base.Channel.EmployeeTerritories_QueryForCollection(serializedQuery);
        }
    }
}
