//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsumer_NonProxy.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ShippersCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Shippers")]
    [System.SerializableAttribute()]
    public class ShippersCollection : System.ComponentModel.BindingList<BusinessObjects.Shippers> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SuppliersCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Suppliers")]
    [System.SerializableAttribute()]
    public class SuppliersCollection : System.ComponentModel.BindingList<BusinessObjects.Suppliers> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TerritoriesCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Territories")]
    [System.SerializableAttribute()]
    public class TerritoriesCollection : System.ComponentModel.BindingList<BusinessObjects.Territories> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EmployeeTerritoriesCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="EmployeeTerritories")]
    [System.SerializableAttribute()]
    public class EmployeeTerritoriesCollection : System.ComponentModel.BindingList<BusinessObjects.EmployeeTerritories> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrderDetailsCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="OrderDetails")]
    [System.SerializableAttribute()]
    public class OrderDetailsCollection : System.ComponentModel.BindingList<BusinessObjects.OrderDetails> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OrdersCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Orders")]
    [System.SerializableAttribute()]
    public class OrdersCollection : System.ComponentModel.BindingList<BusinessObjects.Orders> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductsCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Products")]
    [System.SerializableAttribute()]
    public class ProductsCollection : System.ComponentModel.BindingList<BusinessObjects.Products> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RegionCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Region")]
    [System.SerializableAttribute()]
    public class RegionCollection : System.ComponentModel.BindingList<BusinessObjects.Region> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CategoriesCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Categories")]
    [System.SerializableAttribute()]
    public class CategoriesCollection : System.ComponentModel.BindingList<BusinessObjects.Categories> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CustomerCustomerDemoCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="CustomerCustomerDemo")]
    [System.SerializableAttribute()]
    public class CustomerCustomerDemoCollection : System.ComponentModel.BindingList<BusinessObjects.CustomerCustomerDemo> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CustomerDemographicsCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="CustomerDemographics")]
    [System.SerializableAttribute()]
    public class CustomerDemographicsCollection : System.ComponentModel.BindingList<BusinessObjects.CustomerDemographics> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CustomersCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Customers")]
    [System.SerializableAttribute()]
    public class CustomersCollection : System.ComponentModel.BindingList<BusinessObjects.Customers> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="EmployeesCollection", Namespace="http://schemas.datacontract.org/2004/07/BusinessObjects", ItemName="Employees")]
    [System.SerializableAttribute()]
    public class EmployeesCollection : System.ComponentModel.BindingList<BusinessObjects.Employees> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INonProxyService")]
    public interface INonProxyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Shippers_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Shippers_SaveCollectionResponse")]
        BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket Shippers_SaveCollection(BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Shippers_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Shippers_SaveEntityResponse")]
        BusinessObjects.Shippers Shippers_SaveEntity(BusinessObjects.Shippers entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Suppliers_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Suppliers_LoadAllResponse")]
        BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket Suppliers_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Suppliers_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Suppliers_QueryForCollectionResponse")]
        BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket Suppliers_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Suppliers_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Suppliers_QueryForEntityResponse")]
        BusinessObjects.Suppliers Suppliers_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Suppliers_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Suppliers_GetByPrimaryKeyResponse")]
        BusinessObjects.Suppliers Suppliers_GetByPrimaryKey(int supplierID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Suppliers_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Suppliers_SaveCollectionResponse")]
        BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket Suppliers_SaveCollection(BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Suppliers_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Suppliers_SaveEntityResponse")]
        BusinessObjects.Suppliers Suppliers_SaveEntity(BusinessObjects.Suppliers entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Territories_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Territories_LoadAllResponse")]
        BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket Territories_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Territories_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Territories_QueryForCollectionResponse")]
        BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket Territories_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Territories_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Territories_QueryForEntityResponse")]
        BusinessObjects.Territories Territories_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Territories_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Territories_GetByPrimaryKeyResponse")]
        BusinessObjects.Territories Territories_GetByPrimaryKey(string territoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Territories_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Territories_SaveCollectionResponse")]
        BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket Territories_SaveCollection(BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Territories_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Territories_SaveEntityResponse")]
        BusinessObjects.Territories Territories_SaveEntity(BusinessObjects.Territories entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/EmployeeTerritories_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/EmployeeTerritories_QueryForEntityResponse")]
        BusinessObjects.EmployeeTerritories EmployeeTerritories_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/EmployeeTerritories_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/EmployeeTerritories_GetByPrimaryKeyResponse")]
        BusinessObjects.EmployeeTerritories EmployeeTerritories_GetByPrimaryKey(int employeeID, string territoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/EmployeeTerritories_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/EmployeeTerritories_SaveCollectionResponse")]
        BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket EmployeeTerritories_SaveCollection(BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/EmployeeTerritories_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/EmployeeTerritories_SaveEntityResponse")]
        BusinessObjects.EmployeeTerritories EmployeeTerritories_SaveEntity(BusinessObjects.EmployeeTerritories entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/OrderDetails_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/OrderDetails_LoadAllResponse")]
        BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket OrderDetails_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/OrderDetails_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/OrderDetails_QueryForCollectionResponse")]
        BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket OrderDetails_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/OrderDetails_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/OrderDetails_QueryForEntityResponse")]
        BusinessObjects.OrderDetails OrderDetails_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/OrderDetails_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/OrderDetails_GetByPrimaryKeyResponse")]
        BusinessObjects.OrderDetails OrderDetails_GetByPrimaryKey(int orderID, int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/OrderDetails_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/OrderDetails_SaveCollectionResponse")]
        BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket OrderDetails_SaveCollection(BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/OrderDetails_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/OrderDetails_SaveEntityResponse")]
        BusinessObjects.OrderDetails OrderDetails_SaveEntity(BusinessObjects.OrderDetails entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Orders_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Orders_LoadAllResponse")]
        BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket Orders_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Orders_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Orders_QueryForCollectionResponse")]
        BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket Orders_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Orders_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Orders_QueryForEntityResponse")]
        BusinessObjects.Orders Orders_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Orders_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Orders_GetByPrimaryKeyResponse")]
        BusinessObjects.Orders Orders_GetByPrimaryKey(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Orders_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Orders_SaveCollectionResponse")]
        BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket Orders_SaveCollection(BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Orders_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Orders_SaveEntityResponse")]
        BusinessObjects.Orders Orders_SaveEntity(BusinessObjects.Orders entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Products_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Products_LoadAllResponse")]
        BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket Products_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Products_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Products_QueryForCollectionResponse")]
        BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket Products_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Products_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Products_QueryForEntityResponse")]
        BusinessObjects.Products Products_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Products_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Products_GetByPrimaryKeyResponse")]
        BusinessObjects.Products Products_GetByPrimaryKey(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Products_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Products_SaveCollectionResponse")]
        BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket Products_SaveCollection(BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Products_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Products_SaveEntityResponse")]
        BusinessObjects.Products Products_SaveEntity(BusinessObjects.Products entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Region_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Region_LoadAllResponse")]
        BusinessObjects.RegionCollection.RegionCollectionWCFPacket Region_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Region_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Region_QueryForCollectionResponse")]
        BusinessObjects.RegionCollection.RegionCollectionWCFPacket Region_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Region_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Region_QueryForEntityResponse")]
        BusinessObjects.Region Region_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Region_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Region_GetByPrimaryKeyResponse")]
        BusinessObjects.Region Region_GetByPrimaryKey(int regionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Region_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Region_SaveCollectionResponse")]
        BusinessObjects.RegionCollection.RegionCollectionWCFPacket Region_SaveCollection(BusinessObjects.RegionCollection.RegionCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Region_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Region_SaveEntityResponse")]
        BusinessObjects.Region Region_SaveEntity(BusinessObjects.Region entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Shippers_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Shippers_LoadAllResponse")]
        BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket Shippers_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Shippers_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Shippers_QueryForCollectionResponse")]
        BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket Shippers_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Shippers_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Shippers_QueryForEntityResponse")]
        BusinessObjects.Shippers Shippers_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Shippers_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Shippers_GetByPrimaryKeyResponse")]
        BusinessObjects.Shippers Shippers_GetByPrimaryKey(int shipperID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Categories_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Categories_LoadAllResponse")]
        BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket Categories_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Categories_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Categories_QueryForCollectionResponse")]
        BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket Categories_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Categories_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Categories_QueryForEntityResponse")]
        BusinessObjects.Categories Categories_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Categories_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Categories_GetByPrimaryKeyResponse")]
        BusinessObjects.Categories Categories_GetByPrimaryKey(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Categories_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Categories_SaveCollectionResponse")]
        BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket Categories_SaveCollection(BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Categories_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Categories_SaveEntityResponse")]
        BusinessObjects.Categories Categories_SaveEntity(BusinessObjects.Categories entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerCustomerDemo_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/CustomerCustomerDemo_LoadAllResponse")]
        BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket CustomerCustomerDemo_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerCustomerDemo_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/CustomerCustomerDemo_QueryForCollectionRespon" +
            "se")]
        BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket CustomerCustomerDemo_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerCustomerDemo_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/CustomerCustomerDemo_QueryForEntityResponse")]
        BusinessObjects.CustomerCustomerDemo CustomerCustomerDemo_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerCustomerDemo_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/CustomerCustomerDemo_GetByPrimaryKeyResponse")]
        BusinessObjects.CustomerCustomerDemo CustomerCustomerDemo_GetByPrimaryKey(string customerID, string customerTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerCustomerDemo_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/CustomerCustomerDemo_SaveCollectionResponse")]
        BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket CustomerCustomerDemo_SaveCollection(BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerCustomerDemo_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/CustomerCustomerDemo_SaveEntityResponse")]
        BusinessObjects.CustomerCustomerDemo CustomerCustomerDemo_SaveEntity(BusinessObjects.CustomerCustomerDemo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerDemographics_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/CustomerDemographics_LoadAllResponse")]
        BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket CustomerDemographics_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerDemographics_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/CustomerDemographics_QueryForCollectionRespon" +
            "se")]
        BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket CustomerDemographics_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerDemographics_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/CustomerDemographics_QueryForEntityResponse")]
        BusinessObjects.CustomerDemographics CustomerDemographics_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerDemographics_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/CustomerDemographics_GetByPrimaryKeyResponse")]
        BusinessObjects.CustomerDemographics CustomerDemographics_GetByPrimaryKey(string customerTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerDemographics_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/CustomerDemographics_SaveCollectionResponse")]
        BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket CustomerDemographics_SaveCollection(BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/CustomerDemographics_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/CustomerDemographics_SaveEntityResponse")]
        BusinessObjects.CustomerDemographics CustomerDemographics_SaveEntity(BusinessObjects.CustomerDemographics entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Customers_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Customers_LoadAllResponse")]
        BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket Customers_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Customers_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Customers_QueryForCollectionResponse")]
        BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket Customers_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Customers_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Customers_QueryForEntityResponse")]
        BusinessObjects.Customers Customers_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Customers_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Customers_GetByPrimaryKeyResponse")]
        BusinessObjects.Customers Customers_GetByPrimaryKey(string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Customers_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Customers_SaveCollectionResponse")]
        BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket Customers_SaveCollection(BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Customers_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Customers_SaveEntityResponse")]
        BusinessObjects.Customers Customers_SaveEntity(BusinessObjects.Customers entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Employees_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/Employees_LoadAllResponse")]
        BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Employees_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/Employees_QueryForCollectionResponse")]
        BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_QueryForCollection(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Employees_QueryForEntity", ReplyAction="http://tempuri.org/INonProxyService/Employees_QueryForEntityResponse")]
        BusinessObjects.Employees Employees_QueryForEntity(string serializedQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Employees_GetByPrimaryKey", ReplyAction="http://tempuri.org/INonProxyService/Employees_GetByPrimaryKeyResponse")]
        BusinessObjects.Employees Employees_GetByPrimaryKey(int employeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Employees_SaveCollection", ReplyAction="http://tempuri.org/INonProxyService/Employees_SaveCollectionResponse")]
        BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_SaveCollection(BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket collection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/Employees_SaveEntity", ReplyAction="http://tempuri.org/INonProxyService/Employees_SaveEntityResponse")]
        BusinessObjects.Employees Employees_SaveEntity(BusinessObjects.Employees entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/EmployeeTerritories_LoadAll", ReplyAction="http://tempuri.org/INonProxyService/EmployeeTerritories_LoadAllResponse")]
        BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket EmployeeTerritories_LoadAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INonProxyService/EmployeeTerritories_QueryForCollection", ReplyAction="http://tempuri.org/INonProxyService/EmployeeTerritories_QueryForCollectionRespons" +
            "e")]
        BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket EmployeeTerritories_QueryForCollection(string serializedQuery);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface INonProxyServiceChannel : WCFConsumer_NonProxy.ServiceReference1.INonProxyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class NonProxyServiceClient : System.ServiceModel.ClientBase<WCFConsumer_NonProxy.ServiceReference1.INonProxyService>, WCFConsumer_NonProxy.ServiceReference1.INonProxyService {
        
        public NonProxyServiceClient() {
        }
        
        public NonProxyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NonProxyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NonProxyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NonProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket Shippers_SaveCollection(BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket collection) {
            return base.Channel.Shippers_SaveCollection(collection);
        }
        
        public BusinessObjects.Shippers Shippers_SaveEntity(BusinessObjects.Shippers entity) {
            return base.Channel.Shippers_SaveEntity(entity);
        }
        
        public BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket Suppliers_LoadAll() {
            return base.Channel.Suppliers_LoadAll();
        }
        
        public BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket Suppliers_QueryForCollection(string serializedQuery) {
            return base.Channel.Suppliers_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Suppliers Suppliers_QueryForEntity(string serializedQuery) {
            return base.Channel.Suppliers_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Suppliers Suppliers_GetByPrimaryKey(int supplierID) {
            return base.Channel.Suppliers_GetByPrimaryKey(supplierID);
        }
        
        public BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket Suppliers_SaveCollection(BusinessObjects.SuppliersCollection.SuppliersCollectionWCFPacket collection) {
            return base.Channel.Suppliers_SaveCollection(collection);
        }
        
        public BusinessObjects.Suppliers Suppliers_SaveEntity(BusinessObjects.Suppliers entity) {
            return base.Channel.Suppliers_SaveEntity(entity);
        }
        
        public BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket Territories_LoadAll() {
            return base.Channel.Territories_LoadAll();
        }
        
        public BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket Territories_QueryForCollection(string serializedQuery) {
            return base.Channel.Territories_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Territories Territories_QueryForEntity(string serializedQuery) {
            return base.Channel.Territories_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Territories Territories_GetByPrimaryKey(string territoryID) {
            return base.Channel.Territories_GetByPrimaryKey(territoryID);
        }
        
        public BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket Territories_SaveCollection(BusinessObjects.TerritoriesCollection.TerritoriesCollectionWCFPacket collection) {
            return base.Channel.Territories_SaveCollection(collection);
        }
        
        public BusinessObjects.Territories Territories_SaveEntity(BusinessObjects.Territories entity) {
            return base.Channel.Territories_SaveEntity(entity);
        }
        
        public BusinessObjects.EmployeeTerritories EmployeeTerritories_QueryForEntity(string serializedQuery) {
            return base.Channel.EmployeeTerritories_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.EmployeeTerritories EmployeeTerritories_GetByPrimaryKey(int employeeID, string territoryID) {
            return base.Channel.EmployeeTerritories_GetByPrimaryKey(employeeID, territoryID);
        }
        
        public BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket EmployeeTerritories_SaveCollection(BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket collection) {
            return base.Channel.EmployeeTerritories_SaveCollection(collection);
        }
        
        public BusinessObjects.EmployeeTerritories EmployeeTerritories_SaveEntity(BusinessObjects.EmployeeTerritories entity) {
            return base.Channel.EmployeeTerritories_SaveEntity(entity);
        }
        
        public BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket OrderDetails_LoadAll() {
            return base.Channel.OrderDetails_LoadAll();
        }
        
        public BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket OrderDetails_QueryForCollection(string serializedQuery) {
            return base.Channel.OrderDetails_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.OrderDetails OrderDetails_QueryForEntity(string serializedQuery) {
            return base.Channel.OrderDetails_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.OrderDetails OrderDetails_GetByPrimaryKey(int orderID, int productID) {
            return base.Channel.OrderDetails_GetByPrimaryKey(orderID, productID);
        }
        
        public BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket OrderDetails_SaveCollection(BusinessObjects.OrderDetailsCollection.OrderDetailsCollectionWCFPacket collection) {
            return base.Channel.OrderDetails_SaveCollection(collection);
        }
        
        public BusinessObjects.OrderDetails OrderDetails_SaveEntity(BusinessObjects.OrderDetails entity) {
            return base.Channel.OrderDetails_SaveEntity(entity);
        }
        
        public BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket Orders_LoadAll() {
            return base.Channel.Orders_LoadAll();
        }
        
        public BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket Orders_QueryForCollection(string serializedQuery) {
            return base.Channel.Orders_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Orders Orders_QueryForEntity(string serializedQuery) {
            return base.Channel.Orders_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Orders Orders_GetByPrimaryKey(int orderID) {
            return base.Channel.Orders_GetByPrimaryKey(orderID);
        }
        
        public BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket Orders_SaveCollection(BusinessObjects.OrdersCollection.OrdersCollectionWCFPacket collection) {
            return base.Channel.Orders_SaveCollection(collection);
        }
        
        public BusinessObjects.Orders Orders_SaveEntity(BusinessObjects.Orders entity) {
            return base.Channel.Orders_SaveEntity(entity);
        }
        
        public BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket Products_LoadAll() {
            return base.Channel.Products_LoadAll();
        }
        
        public BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket Products_QueryForCollection(string serializedQuery) {
            return base.Channel.Products_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Products Products_QueryForEntity(string serializedQuery) {
            return base.Channel.Products_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Products Products_GetByPrimaryKey(int productID) {
            return base.Channel.Products_GetByPrimaryKey(productID);
        }
        
        public BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket Products_SaveCollection(BusinessObjects.ProductsCollection.ProductsCollectionWCFPacket collection) {
            return base.Channel.Products_SaveCollection(collection);
        }
        
        public BusinessObjects.Products Products_SaveEntity(BusinessObjects.Products entity) {
            return base.Channel.Products_SaveEntity(entity);
        }
        
        public BusinessObjects.RegionCollection.RegionCollectionWCFPacket Region_LoadAll() {
            return base.Channel.Region_LoadAll();
        }
        
        public BusinessObjects.RegionCollection.RegionCollectionWCFPacket Region_QueryForCollection(string serializedQuery) {
            return base.Channel.Region_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Region Region_QueryForEntity(string serializedQuery) {
            return base.Channel.Region_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Region Region_GetByPrimaryKey(int regionID) {
            return base.Channel.Region_GetByPrimaryKey(regionID);
        }
        
        public BusinessObjects.RegionCollection.RegionCollectionWCFPacket Region_SaveCollection(BusinessObjects.RegionCollection.RegionCollectionWCFPacket collection) {
            return base.Channel.Region_SaveCollection(collection);
        }
        
        public BusinessObjects.Region Region_SaveEntity(BusinessObjects.Region entity) {
            return base.Channel.Region_SaveEntity(entity);
        }
        
        public BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket Shippers_LoadAll() {
            return base.Channel.Shippers_LoadAll();
        }
        
        public BusinessObjects.ShippersCollection.ShippersCollectionWCFPacket Shippers_QueryForCollection(string serializedQuery) {
            return base.Channel.Shippers_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Shippers Shippers_QueryForEntity(string serializedQuery) {
            return base.Channel.Shippers_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Shippers Shippers_GetByPrimaryKey(int shipperID) {
            return base.Channel.Shippers_GetByPrimaryKey(shipperID);
        }
        
        public BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket Categories_LoadAll() {
            return base.Channel.Categories_LoadAll();
        }
        
        public BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket Categories_QueryForCollection(string serializedQuery) {
            return base.Channel.Categories_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Categories Categories_QueryForEntity(string serializedQuery) {
            return base.Channel.Categories_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Categories Categories_GetByPrimaryKey(int categoryID) {
            return base.Channel.Categories_GetByPrimaryKey(categoryID);
        }
        
        public BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket Categories_SaveCollection(BusinessObjects.CategoriesCollection.CategoriesCollectionWCFPacket collection) {
            return base.Channel.Categories_SaveCollection(collection);
        }
        
        public BusinessObjects.Categories Categories_SaveEntity(BusinessObjects.Categories entity) {
            return base.Channel.Categories_SaveEntity(entity);
        }
        
        public BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket CustomerCustomerDemo_LoadAll() {
            return base.Channel.CustomerCustomerDemo_LoadAll();
        }
        
        public BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket CustomerCustomerDemo_QueryForCollection(string serializedQuery) {
            return base.Channel.CustomerCustomerDemo_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.CustomerCustomerDemo CustomerCustomerDemo_QueryForEntity(string serializedQuery) {
            return base.Channel.CustomerCustomerDemo_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.CustomerCustomerDemo CustomerCustomerDemo_GetByPrimaryKey(string customerID, string customerTypeID) {
            return base.Channel.CustomerCustomerDemo_GetByPrimaryKey(customerID, customerTypeID);
        }
        
        public BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket CustomerCustomerDemo_SaveCollection(BusinessObjects.CustomerCustomerDemoCollection.CustomerCustomerDemoCollectionWCFPacket collection) {
            return base.Channel.CustomerCustomerDemo_SaveCollection(collection);
        }
        
        public BusinessObjects.CustomerCustomerDemo CustomerCustomerDemo_SaveEntity(BusinessObjects.CustomerCustomerDemo entity) {
            return base.Channel.CustomerCustomerDemo_SaveEntity(entity);
        }
        
        public BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket CustomerDemographics_LoadAll() {
            return base.Channel.CustomerDemographics_LoadAll();
        }
        
        public BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket CustomerDemographics_QueryForCollection(string serializedQuery) {
            return base.Channel.CustomerDemographics_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.CustomerDemographics CustomerDemographics_QueryForEntity(string serializedQuery) {
            return base.Channel.CustomerDemographics_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.CustomerDemographics CustomerDemographics_GetByPrimaryKey(string customerTypeID) {
            return base.Channel.CustomerDemographics_GetByPrimaryKey(customerTypeID);
        }
        
        public BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket CustomerDemographics_SaveCollection(BusinessObjects.CustomerDemographicsCollection.CustomerDemographicsCollectionWCFPacket collection) {
            return base.Channel.CustomerDemographics_SaveCollection(collection);
        }
        
        public BusinessObjects.CustomerDemographics CustomerDemographics_SaveEntity(BusinessObjects.CustomerDemographics entity) {
            return base.Channel.CustomerDemographics_SaveEntity(entity);
        }
        
        public BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket Customers_LoadAll() {
            return base.Channel.Customers_LoadAll();
        }
        
        public BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket Customers_QueryForCollection(string serializedQuery) {
            return base.Channel.Customers_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Customers Customers_QueryForEntity(string serializedQuery) {
            return base.Channel.Customers_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Customers Customers_GetByPrimaryKey(string customerID) {
            return base.Channel.Customers_GetByPrimaryKey(customerID);
        }
        
        public BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket Customers_SaveCollection(BusinessObjects.CustomersCollection.CustomersCollectionWCFPacket collection) {
            return base.Channel.Customers_SaveCollection(collection);
        }
        
        public BusinessObjects.Customers Customers_SaveEntity(BusinessObjects.Customers entity) {
            return base.Channel.Customers_SaveEntity(entity);
        }
        
        public BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_LoadAll() {
            return base.Channel.Employees_LoadAll();
        }
        
        public BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_QueryForCollection(string serializedQuery) {
            return base.Channel.Employees_QueryForCollection(serializedQuery);
        }
        
        public BusinessObjects.Employees Employees_QueryForEntity(string serializedQuery) {
            return base.Channel.Employees_QueryForEntity(serializedQuery);
        }
        
        public BusinessObjects.Employees Employees_GetByPrimaryKey(int employeeID) {
            return base.Channel.Employees_GetByPrimaryKey(employeeID);
        }
        
        public BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket Employees_SaveCollection(BusinessObjects.EmployeesCollection.EmployeesCollectionWCFPacket collection) {
            return base.Channel.Employees_SaveCollection(collection);
        }
        
        public BusinessObjects.Employees Employees_SaveEntity(BusinessObjects.Employees entity) {
            return base.Channel.Employees_SaveEntity(entity);
        }
        
        public BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket EmployeeTerritories_LoadAll() {
            return base.Channel.EmployeeTerritories_LoadAll();
        }
        
        public BusinessObjects.EmployeeTerritoriesCollection.EmployeeTerritoriesCollectionWCFPacket EmployeeTerritories_QueryForCollection(string serializedQuery) {
            return base.Channel.EmployeeTerritories_QueryForCollection(serializedQuery);
        }
    }
}
