xcopy /Y /Q ..\..\EntitySpaces\EntitySpaces.Core\bin\Release35\EntitySpaces.Core.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\EntitySpaces.DynamicQuery\bin\Release35\EntitySpaces.DynamicQuery.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\EntitySpaces.Interfaces\bin\Release35\EntitySpaces.Interfaces.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\EntitySpaces.Loader.CF\bin\Release35\EntitySpaces.Loader.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\EntitySpaces.LoaderMT.CF\bin\Release35\EntitySpaces.LoaderMT.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\Providers\EntitySpaces.SQLiteProvider.CF\bin\Release35\EntitySpaces.SQLiteProvider.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\Providers\EntitySpaces.SqlServerCeProvider.CF\bin\Release35\EntitySpaces.SqlServerCeProvider.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\Providers\EntitySpaces.SybaseSqlAnywhereProvider.CF\bin\Release35\EntitySpaces.SybaseSqlAnywhereProvider.CF.dll
xcopy /Y /Q ..\..\EntitySpaces\Providers\EntitySpaces.VistaDBProvider.CF\bin\Release35\EntitySpaces.VistaDBProvider.CF.dll
